openapi: 3.0.0
info:
  title: munch-sean
  version: '1.0.0'
servers:
  - url: http://127.0.0.1:3001
paths:
  /healthcheck:
    get:
      summary: healthcheck
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
            default: 5cfff48b-55ec-49fb-a324-af38a21a6de6
      responses:
        '200':
          description: Successful response
  /api/register:
    post:
      summary: user-create
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
            default: 5cfff48b-55ec-49fb-a324-af38a21a6de6
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: 'test@test.com'
                password: ')NdQb)<EBA&b'
      responses:
        '201':
          description: Successful response
  /api/login:
    post:
      summary: user-login
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
            default: 5cfff48b-55ec-49fb-a324-af38a21a6de6
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: 'test@test.com'
                password: ')NdQb)<EBA&b'
      responses:
        '200':
          description: Successful response
  /api/users:
    get:
      summary: user-list
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
            default: 5cfff48b-55ec-49fb-a324-af38a21a6de6
      responses:
        '200':
          description: Successful response
  /api/tasks:
    post:
      summary: task-create
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
            default: 5cfff48b-55ec-49fb-a324-af38a21a6de6
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                dueDate:
                  type: string
                  format: date-time
              example:
                title: 'My Task'
                dueDate: '2024-12-01'
      responses:
        '200':
          description: Successful response
    get:
      summary: task-list
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
            default: 5cfff48b-55ec-49fb-a324-af38a21a6de6
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
        - in: query
          name: status
          required: false
          schema:
            type: string
            default: open
      responses:
        '200':
          description: Successful response
  /api/tasks/{task_id}:
    get:
      summary: task-read
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
            default: 5cfff48b-55ec-49fb-a324-af38a21a6de6
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: application/json
        - in: path
          name: task_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
    put:
      summary: task-update
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
            default: 5cfff48b-55ec-49fb-a324-af38a21a6de6
          default: 5cfff48b-55ec-49fb-a324-af38a21a6de6
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: application/json
        - in: path
          name: task_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                priority:
                  type: string
              example:
                priority: medium
      responses:
        '200':
          description: Successful response
    delete:
      summary: task-delete
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
            default: 5cfff48b-55ec-49fb-a324-af38a21a6de6
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: application/json
        - in: path
          name: task_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
  /api/tasks/assign/{task_id}:
    put:
      summary: task-assign
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
            default: 5cfff48b-55ec-49fb-a324-af38a21a6de6
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: application/json
        - in: path
          name: task_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                userId:
                  type: string
              example:
                status: completed
                userId: 2109da06-2a4a-40fd-b934-b7a54bfcecd9
      responses:
        '200':
          description: Successful response
  /api/tasks/tag/{task_id}:
    put:
      summary: task-tag
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
          default: 5cfff48b-55ec-49fb-a324-af38a21a6de6
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: application/json
        - in: path
          name: task_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
              example:
                - "tag1"
                - "tag2"
      responses:
        '200':
          description: Successful response
  /api/tasks/search:
    post:
      summary: task-search
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
          default: 5cfff48b-55ec-49fb-a324-af38a21a6de6
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              example:
                title: 'name'
      responses:
        '200':
          description: Successful response
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
